Traceback (most recent call last):
  File "/Users/den/miniconda3/envs/cse284/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/den/miniconda3/envs/cse284/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/den/miniconda3/envs/cse284/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/den/miniconda3/envs/cse284/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/den/miniconda3/envs/cse284/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/den/miniconda3/envs/cse284/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/den/miniconda3/envs/cse284/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/den/miniconda3/envs/cse284/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
rng = np.random.RandomState(1)
X = np.dot(rng.rand(2, 2), rng.randn(2, 200)).T
height = X[:,0]+65
weight = X[:,1]+120
data = pd.DataFrame({"height": height, "weight": weight})
data.head()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m rng [38;5;241m=[39m [43mnp[49m[38;5;241m.[39mrandom[38;5;241m.[39mRandomState([38;5;241m1[39m)
[1;32m      2[0m X [38;5;241m=[39m np[38;5;241m.[39mdot(rng[38;5;241m.[39mrand([38;5;241m2[39m, [38;5;241m2[39m), rng[38;5;241m.[39mrandn([38;5;241m2[39m, [38;5;241m200[39m))[38;5;241m.[39mT
[1;32m      3[0m height [38;5;241m=[39m X[:,[38;5;241m0[39m][38;5;241m+[39m[38;5;241m65[39m

[0;31mNameError[0m: name 'np' is not defined
NameError: name 'np' is not defined

